src/Entity/Membres.php
<?php

namespace App\Entity;

use App\Entity\Brands;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;



/**
 * @ORM\Entity(repositoryClass="App\Repository\MembresRepository")
 * @UniqueEntity(fields={"Email"}, message="l'email que vous avez indiqué est déjà utilisé")
 */
class Membres implements UserInterface
{
    
     
   
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")*/

    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=50)
     *
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="5", minMessage="votre mot pass doit etre faire minimum 5")
     * @Assert\EqualTo(propertyPath="Confirme_Password")
     */
    private $Password;



    public $Confirme_Password;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Ville;

    /**
     * @ORM\Column(type="integer")
     */
    private $CodePostal;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Pays;

    /**
     * @ORM\Column(type="array")
     */
    private $Roles=[];

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Brands", inversedBy="membres")
     */
    private $Brands;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Vechicles", inversedBy="membres")
     */
    private $vechicles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="membres", orphanRemoval=true)
     */
    private $bookings;

   
    

    public function __construct()
    {  
        $this->vechicles = new ArrayCollection();
        $this->Brands = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        
        
        
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): self
    {
        $this->Password = $Password;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->CodePostal;
    }

    public function setCodePostal(int $CodePostal): self
    {
        $this->CodePostal = $CodePostal;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->Pays;
    }

    public function setPays(string $Pays): self
    {
        $this->Pays = $Pays;

        return $this;
    }



    public function getUsername(): ?string
    {


        return (string) $this->id;
    }

    public function getSalt(){

     }
    public function eraseCredentials(){

    }

    /**
     * @return array|null
     */
    public function getRoles(): ?array
    {
        $roles = $this->Roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
      
    }

    public function setRoles(array $Roles): self
    {
        $this->Roles = $Roles;

        return $this;
    }

    /**
     * @return Collection|Brands[]
     */
    public function getBrands(): Collection
    {
        return $this->Brands;
    }

    public function addBrand(Brands $brand): self
    {
        if (!$this->Brands->contains($brand)) {
            $this->Brands[] = $brand;
        }

        return $this;
    }

    public function removeBrand(Brands $brand): self
    {
        if ($this->Brands->contains($brand)) {
            $this->Brands->removeElement($brand);
        }

        return $this;
    }

    /**
     * @return Collection|Vechicles[]
     */
    public function getVechicles(): Collection
    {
        return $this->vechicles;
    }

    public function addVechicle(Vechicles $vechicle): self
    {
        if (!$this->vechicles->contains($vechicle)) {
            $this->vechicles[] = $vechicle;
        }

        return $this;
    }

    public function removeVechicle(Vechicles $vechicle): self
    {
        if ($this->vechicles->contains($vechicle)) {
            $this->vechicles->removeElement($vechicle);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setMembres($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getMembres() === $this) {
                $booking->setMembres(null);
            }
        }

        return $this;
    }

    
    

    

    

    
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}

            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
            <link rel="stylesheet" href="{{ asset('css/style.css') }}">
            <link rel="stylesheet" href="{{ asset('css/cardetails.css') }}">

        {% endblock %}
    </head>
    <body>

        {% block menu %}
            <nav class="navbar navbar-expand-lg navbar-dark bg-success" id="nav">
                <a class="navbar-brand" href="#">RentCars</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#nav">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#banner">About us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#carlisting">Car Listing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#contact">Contact</a>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2 d-none d-sm-none d-md-none d-lg-block" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0 btn_all d-none d-sm-none d-md-none d-lg-block" type="submit">Search</button>
                        {% if app.user %}
                        <div class="dropdown pl-1">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-user" aria-hidden="true"></i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item btn btn-secondary btn_all mt-0"><i class="fa fa-user-circle-o" aria-hidden="true"></i>
                            {{ app.user.prenom }}</a><br>
                        {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('admin') }}"  class="dropdown-item btn_all my-2 my-sm-0 ml-0" >
                            Go Dashboard</a>
                        {% endif %}
                        <a href="{{ path('app_logout') }}"  class="dropdown-item my-2 my-sm-0    btn_all" >
                            logout
                        </a>
                        {% endif %}
                        </div>
                        </div>
                        
                        {% if not app.user %}
                        <a href="{{ path('app_login') }}" type="button" class="btn btn-secondary my-2 my-sm-0 ml-2 btn_all open-modal" >
                            login
                        </a>

                        {% else  %}
                        {% endif %}

                        
                    </form>
                </div>

            </nav>
           {% endblock%}
        {% block body %}{% endblock %}

        {% block footer %}
            <footer id="contact" class="mb-0">
                <div class="footer-bottom">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">

                                <p class="copy-right">Copyright &copy; 2017 Car Rental Portal. All Rights Reserved</p>
                            </div>
                            <div class="col-md-5 footer_widget ">
                                <p>Connect with Us:</p>
                                <ul>
                                    <li><a href="http://www.facebook.com" target=_blank><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
                                    <li><a href="http://www.twitter.com" target=_blank><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
                                    <li><a href="https://www.linkedin.com/in/riaze-mohamed-sherif-88512833/" target=_blank><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                                    <li><a href="https://github.com/riaze" target=_blank><i class="fa fa-github" aria-hidden="true"></i></a></li>
                                    <li><a href="https://www.instagram.com" target=_blank><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                </ul>

                            </div>


                        </div>
                    </div>
                </div>
            </footer>
        {% endblock%}

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
                crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>        
        <script src="/js/bootstrap.bundle.min.js"></script>
        
    </body>
</html>

templates/cardetails.html.twig
{% extends 'base.html.twig' %}
{% form_theme createForm 'bootstrap_4_layout.html.twig' %}


    {% block body %}
    <div style=" background: linear-gradient(to right, #0052D4, #65C7F7, #9CECFB);">
    <div class="row">   
        <div class="col-10 offset-1 col-sm-10 offset-sm-1 col-md-6 offset-md-1 col-lg-6 offset-lg-1 col-xl-5 offset-xl-1 "> 

        <table class="blueTable">
        <thead>
        <tr>
        <th>Titles</th>
        <th>Description</th>
        </tr>
        </thead>

        <tbody>
        <tr>
        <td>Brand Name</td>
        <td>{{AllVechicles.Brands.BrandName}}</td>
        </tr>
        <tr>
        <td>Vechicle Title</td>
        <td>{{AllVechicles.vechicleTitle}}</td>
        </tr>
        <tr>
        <td>Vechicle Overview</td>
        <td>{{AllVechicles.VechilcleOverview}}</td>
        </tr>
        <tr>
        <td>Price Per Day</td>
        <td>{{AllVechicles.PrricePerDay}}$</td>
        </tr>
        <tr>
        <td>Full Type</td>
        <td>{{AllVechicles.FuelType}}</td>
        </tr>
        <tr>
        <td>Model Year</td>
        <td>{{AllVechicles.ModelYear|date('Y-m-d')}}</td>
        </tr>
        <tr>
        <td>Seating Capacity</td>
        <td>{{AllVechicles.SeatingCapacity}}</td>
        </tr>
        <tr>
        <td>Air Conditioner</td>
        {% if AllVechicles.AirConditioner == true %}
        <td>Oui</td>
        {% else %}
        <td>No</td>
        {% endif %}
        </tr>
        <tr>
        <td>Power door Lock</td>
        {% if AllVechicles.PowerDoorLocks == true %}
        <td>Oui</td>
        {% else %}
        <td>No</td>
        {% endif %}
        </tr>
        <tr>
        <td>Anti lock braking</td>
        {% if AllVechicles.AntiLockBraking == true %}
        <td>Oui</td>

        {% else %}
        <td>No</td>
        {% endif %}
        </tr>
        <tr>
        <td>break-assist</td>
        {% if AllVechicles.BreakAssist == true %}
        <td>Oui</td>
        {% else %}
        <td>No</td>
        {% endif %}
        </tr>
        <tr>
        <td>Power Steering</td>
        {% if AllVechicles.PowerSteering == true %}
        <td>Oui</td>
        {% else %}
        <td>No</td>
        {% endif %}
        </tr>
        </tbody>
        </table>
   </div> 
   <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-4 offset-md-0 col-lg-4 col-xl-4 mt-4 mb-0 booking"> 
    <p class="text-center text-dark mt-3" style="font-size:30px; font-style:italic;">Book this Car</p>
    {{ form_start(createForm) }}
    {{ form_row(createForm.FromDate, {'attr': {'class': 'bookingMsg'}}) }}
    {{ form_row(createForm.ToDate) }}
    {{ form_row(createForm.Message) }}
     
   
    <input type="submit" value="BooK Now" class="btn btn-success  px-3 register">
     {{ form_end(createForm) }}
    {% if UserNotLogin == true  %}
        <p class="text-center text-danger mt-3 demo" style="font-size:20px; font-style:bold;">Pls login for booking</p>
    {% endif %}
    {% if PrintBookingMsg == true %}
        <p class="text-center text-dark mt-3">congratulation your Booking Is Success!!</p>
    {% endif %}
   </div>
</div>
</div>
 {% endblock  %}
 

templates/changepassword.html.twig
{% form_theme createForm 'bootstrap_4_layout.html.twig' %}
<!DOCTYPE html>
<head>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}

            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
            <link rel="stylesheet" href="{{ asset('css/login.css') }}">

        {% endblock %}
    </head>


            <body>
            <div class="container">
                <div class="row">
                    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                        <div class="card card-signin my-5">
                            <div class="card-body">
                                <h5 class="card-title text-center">Change MTP</h5>
                                {% for message in app.flashes('notice') %}
                                 <div class="alert alert-success">
                                    {{ message }}
                                 </div>
                                {% endfor %}
                                <form method="post" class="form-signin" >

                                    
                                    {{ form_errors(createForm) }}
                                    {{ form_row(createForm._token) }}
                                    <div class="form-label-group">
                                       {{ form_label(createForm.oldPassword, 'Ancien MTP') }}
                                       {{ form_widget(createForm.oldPassword, {'attr': {'class': 'form-control','label': 'Submit me' }}) }}
                                        
                                    </div>

                                    <div class="form-label-group">
                                           {{ form_label(createForm.plainPassword, 'Nouveau  MTP') }}
                                          {{ form_widget(createForm.plainPassword, {'attr': {'class': 'form-control', 'placeholder' : 'Ancien MTP'}}) }}
                                          
                                    </div>
                                      {{  form_row(createForm.submit, {'attr': {'class': 'btn btn-lg btn-primary btn-block text-uppercase'}}) }} 
                                       <a href="{{ path('index')}}" class="btn btn-lg btn-primary btn-block text-uppercase mt-3 reg" >Accueil</a>
                                    
                                   
                              
                                </form>
                               
                              
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
            <script src="/js/bootstrap.bundle.min.js"></script>
            </body>


    </html>

templates/index.html.twig
{% extends 'base.html.twig' %}
    {% block body %}



        <section id="banner" class="banner-section">
            <div class="container">

                <div class="div_zindex">
                    <div class="row">
                        <div class="col-md-5 offset-md-7 ">
                            <div class="banner_content">
                                <h1>Find the right car for you.</h1>
                                <p>We have more than a thousand cars for you to choose. </p>
                                <a href="#" class="btn btn_all">Read More <span class="angle_arrow"><i class="fa fa-angle-right" aria-hidden="true"></i></span></a> </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="section-padding gray-bg ">
            <div class="container">
                <div class="section-header text-center">
                    <h2>Find the Best <span>CarForYou</span></h2>
                    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.</p>
                </div>
                <div class="row" id="carlisting">

                    <!-- Nav tabs -->
                    
                        <ul class="col-12" style="text-align:center;">
                            <li role="presentation" class="active btn text-center text-white btn_all">New Car</li>
                        </ul>
                    
                    <!-- Recently Listed New Cars -->
                    


                    {% for AllVechicles in AllVechicles -%}
                           
                    <div class="col-lg-3 recent-car-list">        
                        <div class="car-info-box"><a href="{{ path('carDetails', {'id':AllVechicles.id}) }}"><img src="img/{{AllVechicles.Vimage1}}" height="150" width="200" class="img-responsive" alt="image"></a>
                            <ul>
                                <li><i class="fa fa-car" aria-hidden="true"></i>{{AllVechicles.FuelType}}</li>
                                <li><i class="fa fa-calendar" aria-hidden="true"></i>{{AllVechicles.PrricePerDay}}</li>
                                <li><i class="fa fa-user" aria-hidden="true"></i> {{AllVechicles.SeatingCapacity}}</li>
                            </ul>
                        </div>
                        <div class="car-title-m">
                            <h6><a href="#">{{AllVechicles.Brands.BrandName}}, {{AllVechicles.vechicleTitle}}</a></h6>
                            <span class="price">{{AllVechicles.PrricePerDay}}  $/Day</span>
                        </div>
                        <div class="inventory_info_m">
                            <p>{{AllVechicles.VechilcleOverview}}</p>
                        </div> 
                    </div> 
                    {%- endfor %}   
                </div>
            </div>                      
        </section>


    {% endblock %}

templates/login.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<form action="{{ path('membres_login') }}" method="post">
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" required name="email" class="form-control ml-3 " id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">

    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" required name="mdp" class="form-control ml-5 mt-2" id="exampleInputPassword1" placeholder="Password">
    </div>

    <button type="submit" class="btn btn-primary btn_all">Login</button>
</form>
{% endblock %}

templates/popup.html.twig
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Login</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form method="post">
        {% if error %}
            <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
        {% endif %}

        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" value="{{ last_username }}" name="Email" id="inputEmail" class="form-control" placeholder=" Email" required autofocus>

        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
        </div>

        <input type="hidden" name="_csrf_token"
               value="{{ csrf_token('authenticate') }}"
        >
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary btn_all" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary btn_all">Login</button>
        </div>
        <a href="{{ 'register' }}" class="btn mb-1 btn_all">Not Register Yet</a>


    </form>
</div>

templates/register.html.twig
{% extends 'base.html.twig' %}
{% form_theme createForm 'bootstrap_4_layout.html.twig' %}
{% block body %}


    <div class="row">
        <div class="col-lg-6 offset-lg-3">
            <div class="container reg_form_size">
                <h3 class="text-center mt-2 text-center">Register</h3>

                <h4 class="btn btn-sm btn-success">{{ message }}</h4>

            {{ form_start(createForm) }}
            {{ form_widget(createForm) }}


              <input type="submit" value="Register" class="btn btn-success  mb-5 px-5 register">

            {{ form_end(createForm) }}
            </div>
        </div>
    </div>
    
{% endblock %}

templates/user.html.twig
{% block body %}


    {% include 'index.html.twig' %}

{% endblock %}